package com.mogul.pojo;

public class ActivityRemark {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.noteContent
     *备注信息
     * @mbg.generated
     */
    private String notecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.createTime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.createBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.editTime
     *
     * @mbg.generated
     */
    private String edittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.editBy
     *
     * @mbg.generated
     */
    private String editby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.editFlag
     *是否修改过的标记
     * @mbg.generated
     */
    private String editflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_activity_remark.activityId
     *
     * @mbg.generated
     */
    private String activityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.id
     *
     * @return the value of tbl_activity_remark.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.id
     *
     * @param id the value for tbl_activity_remark.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.noteContent
     *
     * @return the value of tbl_activity_remark.noteContent
     *
     * @mbg.generated
     */
    public String getNotecontent() {
        return notecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.noteContent
     *
     * @param notecontent the value for tbl_activity_remark.noteContent
     *
     * @mbg.generated
     */
    public void setNotecontent(String notecontent) {
        this.notecontent = notecontent == null ? null : notecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.createTime
     *
     * @return the value of tbl_activity_remark.createTime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.createTime
     *
     * @param createtime the value for tbl_activity_remark.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.createBy
     *
     * @return the value of tbl_activity_remark.createBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.createBy
     *
     * @param createby the value for tbl_activity_remark.createBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.editTime
     *
     * @return the value of tbl_activity_remark.editTime
     *
     * @mbg.generated
     */
    public String getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.editTime
     *
     * @param edittime the value for tbl_activity_remark.editTime
     *
     * @mbg.generated
     */
    public void setEdittime(String edittime) {
        this.edittime = edittime == null ? null : edittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.editBy
     *
     * @return the value of tbl_activity_remark.editBy
     *
     * @mbg.generated
     */
    public String getEditby() {
        return editby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.editBy
     *
     * @param editby the value for tbl_activity_remark.editBy
     *
     * @mbg.generated
     */
    public void setEditby(String editby) {
        this.editby = editby == null ? null : editby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.editFlag
     *
     * @return the value of tbl_activity_remark.editFlag
     *
     * @mbg.generated
     */
    public String getEditflag() {
        return editflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.editFlag
     *
     * @param editflag the value for tbl_activity_remark.editFlag
     *
     * @mbg.generated
     */
    public void setEditflag(String editflag) {
        this.editflag = editflag == null ? null : editflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_activity_remark.activityId
     *
     * @return the value of tbl_activity_remark.activityId
     *
     * @mbg.generated
     */
    public String getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_activity_remark.activityId
     *
     * @param activityid the value for tbl_activity_remark.activityId
     *
     * @mbg.generated
     */
    public void setActivityid(String activityid) {
        this.activityid = activityid == null ? null : activityid.trim();
    }
}
