package com.mogul.pojo;

public class ClueActivityRelation {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue_activity_relation.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue_activity_relation.clueId
     *
     * @mbg.generated
     */
    private String clueid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_clue_activity_relation.activityId
     *
     * @mbg.generated
     */
    private String activityid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_activity_relation.id
     *
     * @return the value of tbl_clue_activity_relation.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_activity_relation.id
     *
     * @param id the value for tbl_clue_activity_relation.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_activity_relation.clueId
     *
     * @return the value of tbl_clue_activity_relation.clueId
     *
     * @mbg.generated
     */
    public String getClueid() {
        return clueid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_activity_relation.clueId
     *
     * @param clueid the value for tbl_clue_activity_relation.clueId
     *
     * @mbg.generated
     */
    public void setClueid(String clueid) {
        this.clueid = clueid == null ? null : clueid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_clue_activity_relation.activityId
     *
     * @return the value of tbl_clue_activity_relation.activityId
     *
     * @mbg.generated
     */
    public String getActivityid() {
        return activityid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_clue_activity_relation.activityId
     *
     * @param activityid the value for tbl_clue_activity_relation.activityId
     *
     * @mbg.generated
     */
    public void setActivityid(String activityid) {
        this.activityid = activityid == null ? null : activityid.trim();
    }
}