package com.mogul.pojo;

public class ContactsRemark {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.noteContent
     *
     * @mbg.generated
     */
    private String notecontent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.createBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.createTime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.editBy
     *
     * @mbg.generated
     */
    private String editby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.editTime
     *
     * @mbg.generated
     */
    private String edittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.editFlag
     *
     * @mbg.generated
     */
    private String editflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts_remark.contactsId
     *
     * @mbg.generated
     */
    private String contactsid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.id
     *
     * @return the value of tbl_contacts_remark.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.id
     *
     * @param id the value for tbl_contacts_remark.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.noteContent
     *
     * @return the value of tbl_contacts_remark.noteContent
     *
     * @mbg.generated
     */
    public String getNotecontent() {
        return notecontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.noteContent
     *
     * @param notecontent the value for tbl_contacts_remark.noteContent
     *
     * @mbg.generated
     */
    public void setNotecontent(String notecontent) {
        this.notecontent = notecontent == null ? null : notecontent.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.createBy
     *
     * @return the value of tbl_contacts_remark.createBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.createBy
     *
     * @param createby the value for tbl_contacts_remark.createBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.createTime
     *
     * @return the value of tbl_contacts_remark.createTime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.createTime
     *
     * @param createtime the value for tbl_contacts_remark.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.editBy
     *
     * @return the value of tbl_contacts_remark.editBy
     *
     * @mbg.generated
     */
    public String getEditby() {
        return editby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.editBy
     *
     * @param editby the value for tbl_contacts_remark.editBy
     *
     * @mbg.generated
     */
    public void setEditby(String editby) {
        this.editby = editby == null ? null : editby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.editTime
     *
     * @return the value of tbl_contacts_remark.editTime
     *
     * @mbg.generated
     */
    public String getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.editTime
     *
     * @param edittime the value for tbl_contacts_remark.editTime
     *
     * @mbg.generated
     */
    public void setEdittime(String edittime) {
        this.edittime = edittime == null ? null : edittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.editFlag
     *
     * @return the value of tbl_contacts_remark.editFlag
     *
     * @mbg.generated
     */
    public String getEditflag() {
        return editflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.editFlag
     *
     * @param editflag the value for tbl_contacts_remark.editFlag
     *
     * @mbg.generated
     */
    public void setEditflag(String editflag) {
        this.editflag = editflag == null ? null : editflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts_remark.contactsId
     *
     * @return the value of tbl_contacts_remark.contactsId
     *
     * @mbg.generated
     */
    public String getContactsid() {
        return contactsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts_remark.contactsId
     *
     * @param contactsid the value for tbl_contacts_remark.contactsId
     *
     * @mbg.generated
     */
    public void setContactsid(String contactsid) {
        this.contactsid = contactsid == null ? null : contactsid.trim();
    }
}