package com.mogul.pojo;

public class Contacts {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.owner
     *
     * @mbg.generated
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.source
     *
     * @mbg.generated
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.customerId
     *
     * @mbg.generated
     */
    private String customerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.fullname
     *
     * @mbg.generated
     */
    private String fullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.appellation
     *
     * @mbg.generated
     */
    private String appellation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.mphone
     *
     * @mbg.generated
     */
    private String mphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.job
     *
     * @mbg.generated
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.birth
     *
     * @mbg.generated
     */
    private String birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.createBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.createTime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.editBy
     *
     * @mbg.generated
     */
    private String editby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.editTime
     *
     * @mbg.generated
     */
    private String edittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.contactSummary
     *
     * @mbg.generated
     */
    private String contactsummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.nextContactTime
     *
     * @mbg.generated
     */
    private String nextcontacttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_contacts.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.id
     *
     * @return the value of tbl_contacts.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.id
     *
     * @param id the value for tbl_contacts.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.owner
     *
     * @return the value of tbl_contacts.owner
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.owner
     *
     * @param owner the value for tbl_contacts.owner
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.source
     *
     * @return the value of tbl_contacts.source
     *
     * @mbg.generated
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.source
     *
     * @param source the value for tbl_contacts.source
     *
     * @mbg.generated
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.customerId
     *
     * @return the value of tbl_contacts.customerId
     *
     * @mbg.generated
     */
    public String getCustomerid() {
        return customerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.customerId
     *
     * @param customerid the value for tbl_contacts.customerId
     *
     * @mbg.generated
     */
    public void setCustomerid(String customerid) {
        this.customerid = customerid == null ? null : customerid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.fullname
     *
     * @return the value of tbl_contacts.fullname
     *
     * @mbg.generated
     */
    public String getFullname() {
        return fullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.fullname
     *
     * @param fullname the value for tbl_contacts.fullname
     *
     * @mbg.generated
     */
    public void setFullname(String fullname) {
        this.fullname = fullname == null ? null : fullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.appellation
     *
     * @return the value of tbl_contacts.appellation
     *
     * @mbg.generated
     */
    public String getAppellation() {
        return appellation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.appellation
     *
     * @param appellation the value for tbl_contacts.appellation
     *
     * @mbg.generated
     */
    public void setAppellation(String appellation) {
        this.appellation = appellation == null ? null : appellation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.email
     *
     * @return the value of tbl_contacts.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.email
     *
     * @param email the value for tbl_contacts.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.mphone
     *
     * @return the value of tbl_contacts.mphone
     *
     * @mbg.generated
     */
    public String getMphone() {
        return mphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.mphone
     *
     * @param mphone the value for tbl_contacts.mphone
     *
     * @mbg.generated
     */
    public void setMphone(String mphone) {
        this.mphone = mphone == null ? null : mphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.job
     *
     * @return the value of tbl_contacts.job
     *
     * @mbg.generated
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.job
     *
     * @param job the value for tbl_contacts.job
     *
     * @mbg.generated
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.birth
     *
     * @return the value of tbl_contacts.birth
     *
     * @mbg.generated
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.birth
     *
     * @param birth the value for tbl_contacts.birth
     *
     * @mbg.generated
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.createBy
     *
     * @return the value of tbl_contacts.createBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.createBy
     *
     * @param createby the value for tbl_contacts.createBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.createTime
     *
     * @return the value of tbl_contacts.createTime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.createTime
     *
     * @param createtime the value for tbl_contacts.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.editBy
     *
     * @return the value of tbl_contacts.editBy
     *
     * @mbg.generated
     */
    public String getEditby() {
        return editby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.editBy
     *
     * @param editby the value for tbl_contacts.editBy
     *
     * @mbg.generated
     */
    public void setEditby(String editby) {
        this.editby = editby == null ? null : editby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.editTime
     *
     * @return the value of tbl_contacts.editTime
     *
     * @mbg.generated
     */
    public String getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.editTime
     *
     * @param edittime the value for tbl_contacts.editTime
     *
     * @mbg.generated
     */
    public void setEdittime(String edittime) {
        this.edittime = edittime == null ? null : edittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.description
     *
     * @return the value of tbl_contacts.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.description
     *
     * @param description the value for tbl_contacts.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.contactSummary
     *
     * @return the value of tbl_contacts.contactSummary
     *
     * @mbg.generated
     */
    public String getContactsummary() {
        return contactsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.contactSummary
     *
     * @param contactsummary the value for tbl_contacts.contactSummary
     *
     * @mbg.generated
     */
    public void setContactsummary(String contactsummary) {
        this.contactsummary = contactsummary == null ? null : contactsummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.nextContactTime
     *
     * @return the value of tbl_contacts.nextContactTime
     *
     * @mbg.generated
     */
    public String getNextcontacttime() {
        return nextcontacttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.nextContactTime
     *
     * @param nextcontacttime the value for tbl_contacts.nextContactTime
     *
     * @mbg.generated
     */
    public void setNextcontacttime(String nextcontacttime) {
        this.nextcontacttime = nextcontacttime == null ? null : nextcontacttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_contacts.address
     *
     * @return the value of tbl_contacts.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_contacts.address
     *
     * @param address the value for tbl_contacts.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}