package com.mogul.pojo;

import com.fasterxml.jackson.annotation.JsonInclude;
@JsonInclude(JsonInclude.Include.NON_NULL)
public class Customer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.owner
     *
     * @mbg.generated
     */
    private String owner;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.website
     *
     * @mbg.generated
     */
    private String website;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.createBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.createTime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.editBy
     *
     * @mbg.generated
     */
    private String editby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.editTime
     *
     * @mbg.generated
     */
    private String edittime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.contactSummary
     *
     * @mbg.generated
     */
    private String contactsummary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.nextContactTime
     *
     * @mbg.generated
     */
    private String nextcontacttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.description
     *
     * @mbg.generated
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_customer.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.id
     *
     * @return the value of tbl_customer.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.id
     *
     * @param id the value for tbl_customer.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.owner
     *
     * @return the value of tbl_customer.owner
     *
     * @mbg.generated
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.owner
     *
     * @param owner the value for tbl_customer.owner
     *
     * @mbg.generated
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.name
     *
     * @return the value of tbl_customer.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.name
     *
     * @param name the value for tbl_customer.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.website
     *
     * @return the value of tbl_customer.website
     *
     * @mbg.generated
     */
    public String getWebsite() {
        return website;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.website
     *
     * @param website the value for tbl_customer.website
     *
     * @mbg.generated
     */
    public void setWebsite(String website) {
        this.website = website == null ? null : website.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.phone
     *
     * @return the value of tbl_customer.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.phone
     *
     * @param phone the value for tbl_customer.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.createBy
     *
     * @return the value of tbl_customer.createBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.createBy
     *
     * @param createby the value for tbl_customer.createBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.createTime
     *
     * @return the value of tbl_customer.createTime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.createTime
     *
     * @param createtime the value for tbl_customer.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.editBy
     *
     * @return the value of tbl_customer.editBy
     *
     * @mbg.generated
     */
    public String getEditby() {
        return editby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.editBy
     *
     * @param editby the value for tbl_customer.editBy
     *
     * @mbg.generated
     */
    public void setEditby(String editby) {
        this.editby = editby == null ? null : editby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.editTime
     *
     * @return the value of tbl_customer.editTime
     *
     * @mbg.generated
     */
    public String getEdittime() {
        return edittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.editTime
     *
     * @param edittime the value for tbl_customer.editTime
     *
     * @mbg.generated
     */
    public void setEdittime(String edittime) {
        this.edittime = edittime == null ? null : edittime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.contactSummary
     *
     * @return the value of tbl_customer.contactSummary
     *
     * @mbg.generated
     */
    public String getContactsummary() {
        return contactsummary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.contactSummary
     *
     * @param contactsummary the value for tbl_customer.contactSummary
     *
     * @mbg.generated
     */
    public void setContactsummary(String contactsummary) {
        this.contactsummary = contactsummary == null ? null : contactsummary.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.nextContactTime
     *
     * @return the value of tbl_customer.nextContactTime
     *
     * @mbg.generated
     */
    public String getNextcontacttime() {
        return nextcontacttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.nextContactTime
     *
     * @param nextcontacttime the value for tbl_customer.nextContactTime
     *
     * @mbg.generated
     */
    public void setNextcontacttime(String nextcontacttime) {
        this.nextcontacttime = nextcontacttime == null ? null : nextcontacttime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.description
     *
     * @return the value of tbl_customer.description
     *
     * @mbg.generated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.description
     *
     * @param description the value for tbl_customer.description
     *
     * @mbg.generated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_customer.address
     *
     * @return the value of tbl_customer.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_customer.address
     *
     * @param address the value for tbl_customer.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}
