package com.mogul.pojo;

public class TranHistory {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.id
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.stage
     *
     * @mbg.generated
     */
    private String stage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.money
     *
     * @mbg.generated
     */
    private String money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.expectedDate
     *
     * @mbg.generated
     */
    private String expecteddate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.createTime
     *
     * @mbg.generated
     */
    private String createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.createBy
     *
     * @mbg.generated
     */
    private String createby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tbl_tran_history.tranId
     *
     * @mbg.generated
     */
    private String tranid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.id
     *
     * @return the value of tbl_tran_history.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.id
     *
     * @param id the value for tbl_tran_history.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.stage
     *
     * @return the value of tbl_tran_history.stage
     *
     * @mbg.generated
     */
    public String getStage() {
        return stage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.stage
     *
     * @param stage the value for tbl_tran_history.stage
     *
     * @mbg.generated
     */
    public void setStage(String stage) {
        this.stage = stage == null ? null : stage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.money
     *
     * @return the value of tbl_tran_history.money
     *
     * @mbg.generated
     */
    public String getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.money
     *
     * @param money the value for tbl_tran_history.money
     *
     * @mbg.generated
     */
    public void setMoney(String money) {
        this.money = money == null ? null : money.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.expectedDate
     *
     * @return the value of tbl_tran_history.expectedDate
     *
     * @mbg.generated
     */
    public String getExpecteddate() {
        return expecteddate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.expectedDate
     *
     * @param expecteddate the value for tbl_tran_history.expectedDate
     *
     * @mbg.generated
     */
    public void setExpecteddate(String expecteddate) {
        this.expecteddate = expecteddate == null ? null : expecteddate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.createTime
     *
     * @return the value of tbl_tran_history.createTime
     *
     * @mbg.generated
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.createTime
     *
     * @param createtime the value for tbl_tran_history.createTime
     *
     * @mbg.generated
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime == null ? null : createtime.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.createBy
     *
     * @return the value of tbl_tran_history.createBy
     *
     * @mbg.generated
     */
    public String getCreateby() {
        return createby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.createBy
     *
     * @param createby the value for tbl_tran_history.createBy
     *
     * @mbg.generated
     */
    public void setCreateby(String createby) {
        this.createby = createby == null ? null : createby.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tbl_tran_history.tranId
     *
     * @return the value of tbl_tran_history.tranId
     *
     * @mbg.generated
     */
    public String getTranid() {
        return tranid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tbl_tran_history.tranId
     *
     * @param tranid the value for tbl_tran_history.tranId
     *
     * @mbg.generated
     */
    public void setTranid(String tranid) {
        this.tranid = tranid == null ? null : tranid.trim();
    }
}