package com.mogul.mapper;

import com.mogul.pojo.Activity;
import com.mogul.pojo.Clue;
import com.mogul.pojo.ClueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ClueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    int insert(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    int insertSelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    List<Clue> selectByExample(ClueExample example);
    List<Clue> selectByJoin(ClueExample example);
    List<Activity> selectByClueAndActivity(String id);
    List<Activity> selectByActivity(@Param("id") String id,@Param("name") String name);
    List<Activity> selectActivityByName(@Param("aname")String aname);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    Clue selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Clue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_clue
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Clue record);
}
